Repository CA-G12/electron, pull requests merged in 2022-08, with the labels that each got.

#2 create file structure
  .gitignore
  Procfile
  package-lock.json
  package.json
  public/css/index.css
  public/css/signin.css
  public/html/signin.html
  public/index.html
  public/js/index.js
  public/js/signin.js
  server/app.js
  server/database/config/connection.js
  server/database/queries/build.sql
  server/database/queries/getData.js
  server/index.js
Labels: done

#4 PAIR PROGRAMMING ALL COMMITS ARE DONE BY BOTH OF US
  public/index.html
  server/app.js
  server/database/config/connection.js
  server/database/queries/build.sql
  server/database/queries/getData.js
  server/index.js
  server/router/router.js
Labels: done

#6 change ssl
  server/database/config/connection.js
Labels: done

#8 home page styling
  img/logo.svg.ico
  public/css/index.css
  public/css/signin.css
  public/html/signin.html
  public/index.html
  public/js/index.js
  public/js/signin.js
Labels: done

#10 create the btn in header page
  public/css/index.css
  public/img/logo.svg.ico
  public/index.html
  public/js/index.js
Labels: done

#12 link database
  img/logo.svg.ico
  public/css/index.css
  public/img/logo.svg.ico
  public/index.html
  public/js/index.js
  server/app.js
  server/database/config/connection.js
  server/database/queries/build.sql
Labels: done

#14 create seller pop up
  public/css/index.css
  public/index.html
  public/js/index.js
  server/database/queries/build.sql
  server/database/queries/getData.js
Labels: done

#16 create form and add functionality
  package-lock.json
  package.json
  public/css/index.css
  public/index.html
  public/js/index.js
  server/database/queries/postData.js
  server/router/router.js
Labels: awaiting-review

#20 tests
  server/app.js
  tests/server-tests.test.js
Labels: done

#21 heroku
  server/database/config/connection.js
Labels: done

#23 Update README.md
  README.md
Labels: in-progress

#25 make selections clearer
  public/index.html
Labels: awaiting-review
